
set(Libpwinterface pwinterface)
IF(QMC_BUILD_STATIC)
  set(Libpwinterface libpwinterface.a)
ENDIF(QMC_BUILD_STATIC)

IF(PWI_INCLUDE_DIRS)

  FIND_PATH(PWINTERFACE_INCLUDE_DIR pwinterface.h ${PWI_INCLUDE_DIRS})
  FIND_LIBRARY(PWINTERFACE_LIBRARY ${Libpwinterface} ${PWI_LIBRARY_DIRS})

ELSE(PWI_INCLUDE_DIRS)

  FIND_PATH(PWINTERFACE_INCLUDE_DIR pwinterface.h $ENV{PWINTERFACE_HOME} ${PWINTERFACE_HOME}/include)
  FIND_LIBRARY(PWINTERFACE_LIBRARIES ${Libpwinterface} ${PWINTERFACE_HOME}/lib $ENV{PWINTERFACE_HOME})

ENDIF(PWI_INCLUDE_DIRS)

IF(PWINTERFACE_INCLUDE_DIR AND PWINTERFACE_LIBRARIES)
  MESSAGE(STATUS "PWINTERFACE_INCLUDE_DIR=${PWINTERFACE_INCLUDE_DIR}")
  MESSAGE(STATUS "PWINTERFACE_LIBRARIES=${PWINTERFACE_LIBRARIES}")
  SET(PWINTERFACE_FOUND TRUE)

  #  find_file(h5settings libhdf5.settings ${QMC_LIBRARY_PATHS})
  #  exec_program(grep  
  #    ARGS libraries ${h5settings}
  #    OUTPUT_VARIABLE HDF5_EXTRA_LIBS
  #    RETURN_VALUE mycheck
  #    )
  #  if(HDF5_EXTRA_LIBS MATCHES "sz")
  #    STRING(REGEX MATCHALL "[-][L]([^ ;])+" HDF5_EXTRA_LIBS_LINK  ${HDF5_EXTRA_LIBS})
  #    STRING(REGEX REPLACE "[-][L]" "" SZLIB_PATH ${HDF5_EXTRA_LIBS_LINK})
  #    find_library(SZLIB_LIBRARIES sz ${SZLIB_PATH})
  #    if(SZLIB_LIBRARIES)
  #      MESSAGE(STATUS "SZLIB_LIBRARIES="${SZLIB_LIBRARIES})
  #      set(SZLIB_FOUND TRUE)
  #    endif(SZLIB_LIBRARIES)
  #  endif(HDF5_EXTRA_LIBS MATCHES "sz")
ELSE()
  SET(PWINTERFACE_FOUND FALSE)
ENDIF()

MARK_AS_ADVANCED(
  PWINTERFACE_INCLUDE_DIR 
  PWINTERFACE_LIBRARIES 
  PWINTERFACE_FOUND
)
